name: "pre-release"

on:
  push:
    branches:
      - "v2"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.16.7"
      - name: "Build"
        run: |
          go build
          tar -cvzf learner-recover.tar.gz learner-recover rpo.sh recover.sh fetcher.sh config

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            learner-recover.tar.gz
